[package]
name = "rb"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.10.2", features = ["rustls-0_23"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["full"]}
uuid = { version = "1.16.0", features = ["v4", "serde"]}
log = "0.4.26"
clap = "4.5.36"
futures = "0.3.31"
base64 = "0.23.1"
# rb_client = { path = "../rb_client" }
# rb_server = { path = "../rb_server" }
